MONGODB_URI: mongodb://user:password@localhost:27017/product-db
REDIS_HOST: localhost

spring:
  application:
    name: product
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
mongock:
  migration-scan-package:
    - "com.kam.product.migration"
