version: '3.1'

services:
  product-db:
    image: mongo:4.4.19-rc0-focal
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - "./.data/db:/var/lib/mongodb"
    environment:
      MONGO_INITDB_DATABASE: product-db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@product-db:27017/
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
